name: Build and Test

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
      
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration Release --framework net8.0-windows
      
    - name: Test with Coverage
      run: dotnet test --no-build --configuration Release --framework net8.0-windows --collect:"XPlat Code Coverage" --results-directory ./coverage

    - name: Generate coverage report
      uses: danielpalme/ReportGenerator-GitHub-Action@5.1.4
      with:
        reports: './coverage/**/coverage.cobertura.xml'
        targetdir: './coverage/report'
        reporttypes: 'Html;HtmlSummary'
        title: 'Code Coverage Report'

    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: './coverage/report'
      continue-on-error: true

    - name: Check coverage threshold
      run: |
        $coverage = Select-Xml -Path "./coverage/**/coverage.cobertura.xml" -XPath "//coverage/@line-rate" | Select-Object -ExpandProperty Node | Select-Object -ExpandProperty Value
        $coveragePercent = [math]::Round([double]$coverage * 100, 2)
        Write-Host "Current line coverage: $coveragePercent%"
        if ($coveragePercent -lt 70) {
          Write-Error "Code coverage ($coveragePercent%) is below the required threshold of 70%"
          exit 1
        }